// 镜像后端 AdminPermissions，供前端显隐控制。
export const P = {
  systemAdminManage: 'system.admin.manage',
  systemRoleManage: 'system.role.manage',
  systemAuditView: 'system.audit.view',
  userView: 'user.view',
  userMembershipEdit: 'user.membership.edit',
  userStatusEdit: 'user.status.edit',
  userPasswordReset: 'user.password.reset',
  membershipCorrectionView: 'membership.correction.view',
  membershipCorrectionReview: 'membership.correction.review',
  orderView: 'order.view',
  orderRefundRequest: 'order.refund.request',
  orderRefundApprove: 'order.refund.approve',
  orderReconcile: 'order.reconcile',
  silkView: 'silk.view',
  silkAdjustSmall: 'silk.adjust.small',
  silkAdjustLarge: 'silk.adjust.large',
  silkConfig: 'silk.config',
  planView: 'plan.view',
  planEdit: 'plan.edit',
  signalView: 'signal.view',
  signalConfig: 'signal.config',
  analyticsView: 'analytics.view',
  analyticsUserTracking: 'analytics.user.tracking',
  tokenView: 'token.view',
  tokenManage: 'token.manage',
  aiOrganizationView: 'ai.organization.view',
  aiOrganizationManage: 'ai.organization.manage',
  aiCredentialView: 'ai.credential.view',
  aiCredentialManage: 'ai.credential.manage',
  aiUsageView: 'ai.usage.view',
  aiAuditView: 'ai.audit.view',
  aiBillingReconcile: 'ai.billing.reconcile',
  aiOpsView: 'ai.ops.view',
  aiOpsManage: 'ai.ops.manage',
} as const
